/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import datos.*;
import presentacion.IfrmHistorialProfesor;

/**
 *
 * @author USER
 */
public class FrmPrincipal extends javax.swing.JFrame {
    ListaEstudiantes lista;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dspEscritorio = new javax.swing.JDesktopPane();
        btnRegistro = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnHistorialProfesor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnHistorial.setText("Historial de Registro");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        btnHistorialProfesor.setText("Historial de Profesores");
        btnHistorialProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialProfesorActionPerformed(evt);
            }
        });

        dspEscritorio.setLayer(btnRegistro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dspEscritorio.setLayer(btnHistorial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dspEscritorio.setLayer(btnHistorialProfesor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dspEscritorioLayout = new javax.swing.GroupLayout(dspEscritorio);
        dspEscritorio.setLayout(dspEscritorioLayout);
        dspEscritorioLayout.setHorizontalGroup(
            dspEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dspEscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistro)
                .addGap(18, 18, 18)
                .addComponent(btnHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistorialProfesor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dspEscritorioLayout.setVerticalGroup(
            dspEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dspEscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dspEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistro)
                    .addComponent(btnHistorial)
                    .addComponent(btnHistorialProfesor))
                .addContainerGap(259, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dspEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dspEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
       IfrmEstudiante ventana = new IfrmEstudiante();
       dspEscritorio.add(ventana);
       ventana.setLocation(
    (dspEscritorio.getWidth() - ventana.getWidth()) / 2,
    (dspEscritorio.getHeight() - ventana.getHeight()) / 2
);
       ventana.setVisible(true);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
       IfrmHistorialRegistro historial= new IfrmHistorialRegistro();
       dspEscritorio.add(historial);
       historial.setLocation(
    (dspEscritorio.getWidth() - historial.getWidth()) / 2,
    (dspEscritorio.getHeight() - historial.getHeight()) / 2
);
       historial.setVisible(true);
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnHistorialProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialProfesorActionPerformed
                                                   
    IfrmHistorialProfesor historialProfesor = new IfrmHistorialProfesor();
    dspEscritorio.add(historialProfesor);
    historialProfesor.setLocation(
        (dspEscritorio.getWidth() - historialProfesor.getWidth()) / 2,
        (dspEscritorio.getHeight() - historialProfesor.getHeight()) / 2
    );
    historialProfesor.setVisible(true);


    // TODO add your handling code here:
    }//GEN-LAST:event_btnHistorialProfesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnHistorialProfesor;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JDesktopPane dspEscritorio;
    // End of variables declaration//GEN-END:variables
}
