/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import datos.*;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import datos.ListaEstudiantes;
import java.util.*;
import javax.swing.JOptionPane;

/**
 * Clase IfrmEliminar - Ventana interna para eliminar registros de estudiantes o docentes.
 * Permite al usuario ingresar un código y seleccionar el tipo de usuario a eliminar.
 * 
 */
public class IfrmEliminar extends javax.swing.JInternalFrame {

    /**
     * Constructor de la clase IfrmEliminar.
     * Inicializa los componentes gráficos de la ventana.
     */
    public IfrmEliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipo = new javax.swing.ButtonGroup();
        panFondo = new javax.swing.JPanel();
        panCodigo = new RoundedPanel();
        lblMensaje = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnEliminar = new FlatButton("Eliminar");
        lblLogo = new javax.swing.JLabel();
        jrbEstudiante = new javax.swing.JRadioButton();
        jrbDocente = new javax.swing.JRadioButton();

        setClosable(true);

        panFondo.setBackground(new java.awt.Color(255, 255, 255));

        panCodigo.setBackground(new java.awt.Color(11, 55, 97));

        lblMensaje.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 255, 255));
        lblMensaje.setText("Ingrese el código del estudiante o docente a eliminar:");

        txtCodigo.setBackground(new java.awt.Color(11, 55, 97));
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setBorder(null);

        javax.swing.GroupLayout panCodigoLayout = new javax.swing.GroupLayout(panCodigo);
        panCodigo.setLayout(panCodigoLayout);
        panCodigoLayout.setHorizontalGroup(
            panCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCodigoLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(panCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodigo)
                    .addComponent(jSeparator1))
                .addGap(55, 55, 55))
        );
        panCodigoLayout.setVerticalGroup(
            panCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCodigoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        btnEliminar.setBackground(new java.awt.Color(11, 55, 97));
        btnEliminar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo-.png"))); // NOI18N

        btgTipo.add(jrbEstudiante);
        jrbEstudiante.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jrbEstudiante.setText("Estudiante");
        jrbEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEstudianteActionPerformed(evt);
            }
        });

        btgTipo.add(jrbDocente);
        jrbDocente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jrbDocente.setText("Docente");

        javax.swing.GroupLayout panFondoLayout = new javax.swing.GroupLayout(panFondo);
        panFondo.setLayout(panFondoLayout);
        panFondoLayout.setHorizontalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jrbEstudiante)
                .addGap(65, 65, 65)
                .addComponent(jrbDocente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panFondoLayout.setVerticalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbEstudiante)
                    .addComponent(jrbDocente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
     * Acción del botón "Eliminar".
     * Verifica que se haya ingresado un código y que se haya seleccionado el tipo de usuario.
     * Luego elimina al estudiante o docente según el código ingresado.
     */    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String codigo = txtCodigo.getText().trim();

        // Validación: campo de código vacío
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "⚠️ Debe ingresar un código válido.",
                "Error",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        
        // Validación: tipo de usuario no seleccionado

        if(btgTipo.getSelection() == null){
            JOptionPane.showMessageDialog(
                this,
                "Por favor, seleccione el tipo de usuario a eliminar",
                "Error",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
          // Eliminar estudiante
        if (jrbEstudiante.isSelected()) {

            ListaEstudiantes lista = new ListaEstudiantes();
            boolean ok = lista.eliminarEstudiante(codigo);
            if (ok) {
                JOptionPane.showMessageDialog(this, "✅ Estudiante eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "❌ No se encontró ningún estudiante con ese código.", "No encontrado", JOptionPane.ERROR_MESSAGE);
            }
            // Eliminar docente
        } else if (jrbDocente.isSelected()) {
            ListaIngresosDocente lista = new ListaIngresosDocente();
            boolean ok = lista.eliminarPorCodigo(codigo);
            if (ok) {
                JOptionPane.showMessageDialog(this, "✅ Docente eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "❌ No se encontró ningún docente con ese código.", "No encontrado", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        // Limpiar campo y dejar el foco listo para un nuevo ingreso
        txtCodigo.setText("");
        txtCodigo.requestFocus();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jrbEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbEstudianteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTipo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton jrbDocente;
    private javax.swing.JRadioButton jrbEstudiante;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JPanel panCodigo;
    private javax.swing.JPanel panFondo;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
