/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import datos.ListaEstudiantes;
import entidades.Estudiante;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class IfrmHistorialRegistro extends javax.swing.JInternalFrame {
    private ListaEstudiantes lista;
    /**
     * Creates new form IfrmHistorialRegistro
     */
    public IfrmHistorialRegistro() {
        initComponents();
        this.lista= new ListaEstudiantes();
        imprimir();
    }
    
    public void imprimir() {
    ArrayList<Estudiante> estudiantes = lista.leerEstudiantes();
    DefaultTableModel modelo = (DefaultTableModel) tlbHistorial.getModel();
    modelo.setRowCount(0);

    if (estudiantes.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No se encontraron estudiantes guardados.");
    } else {
        
        for (int i = 0; i < estudiantes.size(); i++) {
            Estudiante estudiante = estudiantes.get(i);  
            Object[] fila = new Object[3];
            fila[0] = estudiante.getNombre();
            fila[1] = estudiante.getCodigo();
            fila[2] = estudiante.getEscuela();
            modelo.addRow(fila);
        }
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tlbHistorial = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tlbHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombres y apellidos", "Cod. Matricula", "Escuela Profesional"
            }
        ));
        jScrollPane1.setViewportView(tlbHistorial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tlbHistorial;
    // End of variables declaration//GEN-END:variables
}
